version: 2.1
executors:
  default:
    docker:
      - image: cimg/go:1.17-node

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: node -v
      - run: make check-style-go
      - run: make check-style-webapp

  test:
    executor:
      name: default
    steps:
      - checkout
      - run: node -v
      - run: make test

workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - test
