version: 2.1
executors:
  default:
    docker:
      - image: cimg/go:1.18.5

commands:
  install-node-npm:
    description: Install Node.js and npm
    steps:
      - run:
          name: "Install Node.js and npm"
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
            echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
            nvm install 16.9.1
      - run:
          name: Check current version of node
          command: node -v
      - run:
          name: Check current version of NPM
          command: npm -v

  npm-dependencies:
    description: "Get JavaScript dependencies"
    steps:
      - restore_cache:
          name: Restore npm cache
          key: v2-npm-{{ checksum "./webapp/package-lock.json" }}-{{ arch }}
      - run:
          name: Getting JavaScript dependencies
          command: |
            cd webapp
            NODE_ENV=development npm ci --ignore-scripts --no-save
      - save_cache:
          name: Save npm cache
          key: v2-npm-{{ checksum "./webapp/package-lock.json" }}-{{ arch }}
          paths:
            - ./webapp/node_modules

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - install-node-npm
      - npm-dependencies
      - run: make check-style-go
      - run: make check-style-webapp

  test:
    executor:
      name: default
    steps:
      - checkout
      - install-node-npm
      - npm-dependencies
      - run: make test

workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - test
